import { LandRecord } from '../types/landRecord';

export const INITIAL_MOCK_RECORDS: LandRecord[] = [
  // --- Cumilla Records ---
  {
    id: 'cum-001',
    slNo: 1,
    district: 'কুমিল্লা',
    upazila: 'আদর্শ সদর',
    mouza: 'বরাইচারা',
    jlNo: '১০৪',
    surveyType: 'RS',
    khatianNo: '৪১২',
    dagNo: '১০৮৫',
    ownerDetails: 'মোঃ আব্দুর রশিদ মজুমদার, পিতা- মৃত আছমত আলী মজুমদার (হিস্যা ০.৫০০০); মোঃ সামসুল হক, পিতা- মৃত আছমত আলী (হিস্যা ০.৫০০০)',
    share: '১.০০০০',
    landClass: 'নাল',
    area: '০.২৫০০ একর',
    remarks: 'দাগের পূর্বাংশ',
    extraAttributes: {
      'তৌজি নং': '১২৮/খ',
      'সাবেক দাগ': '৯৮৪',
      'হাল দাগ': '১০৮৫',
      'খাজনা (বার্ষিক)': '৭৫.৫০ টাকা',
    },
    fileName: 'RS_Baraichara_(JL_104)_Kh_412.pdf',
    relativePath: 'Master_LR_Records/কুমিল্লা/আদর্শ সদর/RS_বরাইচারা_(JL_104)/Kh_412_Dag_1085.pdf',
    fileSize: 342000,
    dateIngested: '2026-10-04T10:15:00.000Z',
    verified: true,
  },
  {
    id: 'cum-002',
    slNo: 2,
    district: 'কুমিল্লা',
    upazila: 'আদর্শ সদর',
    mouza: 'বরাইচারা',
    jlNo: '১০৪',
    surveyType: 'RS',
    khatianNo: '৪১২',
    dagNo: '১০৮৬',
    ownerDetails: 'মোঃ আব্দুর রশিদ মজুমদার, পিতা- মৃত আছমত আলী মজুমদার',
    share: '০.৫০০০',
    landClass: 'বাড়ি',
    area: '০.০৮৫০ একর',
    remarks: 'বসতভিটা ও পাকা দালান',
    extraAttributes: {
      'তৌজি নং': '১২৮/খ',
      'সাবেক দাগ': '৯৮৫',
      'হাল দাগ': '১০৮৬',
      'খাজনা (বার্ষিক)': '১২০.০০ টাকা',
    },
    fileName: 'RS_Baraichara_(JL_104)_Kh_412.pdf',
    relativePath: 'Master_LR_Records/কুমিল্লা/আদর্শ সদর/RS_বরাইচারা_(JL_104)/Kh_412_Dag_1086.pdf',
    fileSize: 342000,
    dateIngested: '2026-10-04T10:15:00.000Z',
    verified: true,
  },
  {
    id: 'cum-003',
    slNo: 3,
    district: 'কুমিল্লা',
    upazila: 'আদর্শ সদর',
    mouza: 'বরাইচারা',
    jlNo: '১০৪',
    surveyType: 'SA',
    khatianNo: '১৮৫',
    dagNo: '৬৫০',
    ownerDetails: 'শ্রীমতি কিরণবালা ভৌমিক, স্বামী- রমেশ চন্দ্র ভৌমিক',
    share: '০.৭৫০০',
    landClass: 'পুকুর',
    area: '০.৩৪০০ একর',
    remarks: 'পুকুর পাড়ে সুপারি বাগান বিদ্যমান',
    extraAttributes: {
      'তৌজি নং': '৮৪/ক',
      'সাবেক দাগ': '৫১২',
      'হাল দাগ': '৬৫০',
      'খাজনা (বার্ষিক)': '৮৫.০০ টাকা',
    },
    fileName: 'SA_Baraichara_(JL_104)_Kh_185.pdf',
    relativePath: 'Master_LR_Records/কুমিল্লা/আদর্শ সদর/SA_বরাইচারা_(JL_104)/Kh_185_Dag_650.pdf',
    fileSize: 512000,
    dateIngested: '2026-10-04T10:15:00.000Z',
    verified: false,
  },
  {
    id: 'cum-004',
    slNo: 4,
    district: 'কুমিল্লা',
    upazila: 'কোতোয়ালী',
    mouza: 'ধর্মপুর',
    jlNo: '৭২',
    surveyType: 'BRS',
    khatianNo: '৮৯',
    dagNo: '৩২৪',
    ownerDetails: 'হাজী মোঃ জালাল উদ্দিন ভূঁইয়া, পিতা- মরহুম করিম বখশ ভূঁইয়া',
    share: '১.০০০০',
    landClass: 'বাণিজ্যিক',
    area: '০.১৫৫০ একর',
    remarks: 'পাকা মার্কেট ভবন সংলগ্ন',
    extraAttributes: {
      'তৌজি নং': '৪৫/১',
      'সাবেক দাগ': '২৮০',
      'হাল দাগ': '৩২৪',
      'খাজনা (বার্ষিক)': '৪৫০.০০ টাকা',
      'বাটা দাগ': '৩২৪/১',
    },
    fileName: 'BRS_Dharmapur_(JL_72)_Kh_89.pdf',
    relativePath: 'Master_LR_Records/কুমিল্লা/কোতোয়ালী/BRS_ধর্মপুর_(JL_72)/Kh_89_Dag_324.pdf',
    fileSize: 420000,
    dateIngested: '2026-10-04T11:00:00.000Z',
    verified: true,
  },
  {
    id: 'cum-005',
    slNo: 5,
    district: 'কুমিল্লা',
    upazila: 'কোতোয়ালী',
    mouza: 'ধর্মপুর',
    jlNo: '৭২',
    surveyType: 'BRS',
    khatianNo: '৮৯',
    dagNo: '৩২৫',
    ownerDetails: 'মোসাঃ নূরজাহান বেগম, স্বামী- হাজী মোঃ জালাল উদ্দিন ভূঁইয়া',
    share: '০.৫০০০',
    landClass: 'বাগান',
    area: '০.১৮০০ একর',
    remarks: 'ফলদ ও বনজ বাগান',
    extraAttributes: {
      'তৌজি নং': '৪৫/১',
      'সাবেক দাগ': '২৮১',
      'হাল দাগ': '৩২৫',
      'খাজনা (বার্ষিক)': '৬০.০০ টাকা',
    },
    fileName: 'BRS_Dharmapur_(JL_72)_Kh_89.pdf',
    relativePath: 'Master_LR_Records/কুমিল্লা/কোতোয়ালী/BRS_ধর্মপুর_(JL_72)/Kh_89_Dag_325.pdf',
    fileSize: 420000,
    dateIngested: '2026-10-04T11:00:00.000Z',
    verified: true,
  },
  {
    id: 'cum-006',
    slNo: 6,
    district: 'কুমিল্লা',
    upazila: 'চৌদ্দগ্রাম',
    mouza: 'সুজানগর',
    jlNo: '৬১',
    surveyType: 'CS',
    khatianNo: '৩১',
    dagNo: '১৪২',
    ownerDetails: 'মৌলভী আলাউদ্দিন আহমেদ, পিতা- মুন্সী সেকান্দর আলী',
    share: '০.৬২৫০',
    landClass: 'নাল',
    area: '০.৫২০০ একর',
    remarks: 'বোরো ও আমন জমি',
    extraAttributes: {
      'তৌজি নং': '৭৭',
      'সাবেক দাগ': '১৩৮',
      'হাল দাগ': '১৪২',
      'খাজনা (বার্ষিক)': '৪৫.০০ টাকা',
    },
    fileName: 'CS_Sujanagar_(JL_61)_Kh_31.pdf',
    relativePath: 'Master_LR_Records/কুমিল্লা/চৌদ্দগ্রাম/CS_সুজানগর_(JL_61)/Kh_31_Dag_142.pdf',
    fileSize: 680000,
    dateIngested: '2026-10-04T11:30:00.000Z',
    verified: true,
  },

  // --- Brahmanbaria Records ---
  {
    id: 'bra-001',
    slNo: 7,
    district: 'ব্রাহ্মণবাড়িয়া',
    upazila: 'ব্রাহ্মণবাড়িয়া সদর',
    mouza: 'মেড্ডা',
    jlNo: '২৮',
    surveyType: 'RS',
    khatianNo: '২৫৪',
    dagNo: '৭৮২',
    ownerDetails: 'আলহাজ্ব দেলোয়ার হোসেন খান, পিতা- মরহুম তোফাজ্জল হোসেন খান',
    share: '১.০০০০',
    landClass: 'ভিটি',
    area: '০.১২২০ একর',
    remarks: 'পাকা সীমানা প্রাচীর বেষ্টিত',
    extraAttributes: {
      'তৌজি নং': '১৯/গ',
      'সাবেক দাগ': '৬৫৪',
      'হাল দাগ': '৭৮২',
      'খাজনা (বার্ষিক)': '১৮০.০০ টাকা',
    },
    fileName: 'RS_Medda_(JL_28)_Kh_254.pdf',
    relativePath: 'Master_LR_Records/ব্রাহ্মণবাড়িয়া/ব্রাহ্মণবাড়িয়া সদর/RS_মেড্ডা_(JL_28)/Kh_254_Dag_782.pdf',
    fileSize: 490000,
    dateIngested: '2026-10-04T12:00:00.000Z',
    verified: true,
  },
  {
    id: 'bra-002',
    slNo: 8,
    district: 'ব্রাহ্মণবাড়িয়া',
    upazila: 'ব্রাহ্মণবাড়িয়া সদর',
    mouza: 'ঘাটুরা',
    jlNo: '৪৫',
    surveyType: 'BRS',
    khatianNo: '১৭৮',
    dagNo: '৫৬৪',
    ownerDetails: 'মোঃ মোখলেছুর রহমান, পিতা- খলিলুর রহমান (অংশ ০.৫০০০); মোঃ মিজানুর রহমান (অংশ ০.৫০০০)',
    share: '১.০০০০',
    landClass: 'নাল',
    area: '০.৪৩৫০ একর',
    remarks: 'তিল ও ধান চাষ উপযোগী',
    extraAttributes: {
      'তৌজি নং': '৩১২',
      'সাবেক দাগ': '৪৯০',
      'হাল দাগ': '৫৬৪',
      'খাজনা (বার্ষিক)': '৯৫.০০ টাকা',
      'বাটা দাগ': '৫৬৪/২',
    },
    fileName: 'BRS_Ghatura_(JL_45)_Kh_178.pdf',
    relativePath: 'Master_LR_Records/ব্রাহ্মণবাড়িয়া/ব্রাহ্মণবাড়িয়া সদর/BRS_ঘাটুরা_(JL_45)/Kh_178_Dag_564.pdf',
    fileSize: 412000,
    dateIngested: '2026-10-04T12:15:00.000Z',
    verified: true,
  },
  {
    id: 'bra-003',
    slNo: 9,
    district: 'ব্রাহ্মণবাড়িয়া',
    upazila: 'ব্রাহ্মণবাড়িয়া সদর',
    mouza: 'ঘাটুরা',
    jlNo: '৪৫',
    surveyType: 'BRS',
    khatianNo: '১৭৮',
    dagNo: '৫৬৫',
    ownerDetails: 'মোঃ মোখলেছুর রহমান, পিতা- খলিলুর রহমান',
    share: '০.৫০০০',
    landClass: 'পুকুর',
    area: '০.২৮০০ একর',
    remarks: 'মৎস্য চাষ প্রকল্প',
    extraAttributes: {
      'তৌজি নং': '৩১২',
      'সাবেক দাগ': '৪৯১',
      'হাল দাগ': '৫৬৫',
      'খাজনা (বার্ষিক)': '৭০.০০ টাকা',
    },
    fileName: 'BRS_Ghatura_(JL_45)_Kh_178.pdf',
    relativePath: 'Master_LR_Records/ব্রাহ্মণবাড়িয়া/ব্রাহ্মণবাড়িয়া সদর/BRS_ঘাটুরা_(JL_45)/Kh_178_Dag_565.pdf',
    fileSize: 412000,
    dateIngested: '2026-10-04T12:15:00.000Z',
    verified: false,
  },
  {
    id: 'bra-004',
    slNo: 10,
    district: 'ব্রাহ্মণবাড়িয়া',
    upazila: 'কসবা',
    mouza: 'তারুয়া',
    jlNo: '১৯',
    surveyType: 'SA',
    khatianNo: '৯৪',
    dagNo: '২১০',
    ownerDetails: 'বাবু অমরেন্দ্র লাল রায় চৌধুরী, পিতা- রায়বাহাদুর উপেন্দ্র লাল রায়',
    share: '১.০০০০',
    landClass: 'বাড়ি',
    area: '০.২২০০ একর',
    remarks: 'পুরাতন কাছারি বাড়ি ও সংলগ্ন আঙিনা',
    extraAttributes: {
      'তৌজি নং': '৫৫/২',
      'সাবেক দাগ': '১৭৫',
      'হাল দাগ': '২১০',
      'খাজনা (বার্ষিক)': '২০০.০০ টাকা',
    },
    fileName: 'SA_Tarua_(JL_19)_Kh_94.pdf',
    relativePath: 'Master_LR_Records/ব্রাহ্মণবাড়িয়া/কসবা/SA_তারুয়া_(JL_19)/Kh_94_Dag_210.pdf',
    fileSize: 580000,
    dateIngested: '2026-10-04T12:45:00.000Z',
    verified: true,
  },
  {
    id: 'bra-005',
    slNo: 11,
    district: 'ব্রাহ্মণবাড়িয়া',
    upazila: 'কসবা',
    mouza: 'তারুয়া',
    jlNo: '১৯',
    surveyType: 'CS',
    khatianNo: '১২',
    dagNo: '৭৮',
    ownerDetails: 'শেখ বোরহান উদ্দিন, পিতা- শেখ আফতাব উদ্দিন',
    share: '০.৫০০০',
    landClass: 'নাল',
    area: '০.৩৬০০ একর',
    remarks: 'দক্ষিণ সীমানায় সরকারি গোপাট',
    extraAttributes: {
      'তৌজি নং': '১২',
      'সাবেক দাগ': '৭০',
      'হাল দাগ': '৭৮',
      'খাজনা (বার্ষিক)': '৩০.০০ টাকা',
    },
    fileName: 'CS_Tarua_(JL_19)_Kh_12.pdf',
    relativePath: 'Master_LR_Records/ব্রাহ্মণবাড়িয়া/কসবা/CS_তারুয়া_(JL_19)/Kh_12_Dag_78.pdf',
    fileSize: 720000,
    dateIngested: '2026-10-04T13:00:00.000Z',
    verified: true,
  },
  {
    id: 'bra-006',
    slNo: 12,
    district: 'ব্রাহ্মণবাড়িয়া',
    upazila: 'নবীনগর',
    mouza: 'রসুলপুর',
    jlNo: '৮৩',
    surveyType: 'RS',
    khatianNo: '৩২০',
    dagNo: '৯৪৫',
    ownerDetails: 'মাওলানা আব্দুল হাকিম, পিতা- মরহুম কাজী কেরামত আলী',
    share: '১.০০০০',
    landClass: 'চালা',
    area: '০.১৫০০ একর',
    remarks: 'উঁচু জমি, সবজি চাষ',
    extraAttributes: {
      'তৌজি নং': '৯১',
      'সাবেক দাগ': '৮৯০',
      'হাল দাগ': '৯৪৫',
      'খাজনা (বার্ষিক)': '৪০.০০ টাকা',
    },
    fileName: 'RS_Rasulpur_(JL_83)_Kh_320.pdf',
    relativePath: 'Master_LR_Records/ব্রাহ্মণবাড়িয়া/নবীনগর/RS_রসুলপুর_(JL_83)/Kh_320_Dag_945.pdf',
    fileSize: 450000,
    dateIngested: '2026-10-04T13:30:00.000Z',
    verified: false,
  },
];

export const DEFAULT_COLUMNS = [
  { id: 'slNo', label: 'ক্রমিক নং', visible: true, order: 1, type: 'number' as const, width: 80 },
  { id: 'mouza', label: 'মৌজা ও জে.এল.', visible: true, order: 2, type: 'text' as const, width: 140 },
  { id: 'surveyType', label: 'জরিপ', visible: true, order: 3, type: 'badge' as const, width: 90 },
  { id: 'khatianNo', label: 'খতিয়ান নং', visible: true, order: 4, type: 'text' as const, width: 110 },
  { id: 'dagNo', label: 'দাগ নং', visible: true, order: 5, type: 'text' as const, width: 100 },
  { id: 'ownerDetails', label: 'মালিক / স্বত্ত্বাধিকারীর বিবরণ', visible: true, order: 6, type: 'text' as const, width: 260 },
  { id: 'share', label: 'হিস্যা / অংশ', visible: true, order: 7, type: 'text' as const, width: 110 },
  { id: 'landClass', label: 'জমির শ্রেণি', visible: true, order: 8, type: 'badge' as const, width: 100 },
  { id: 'area', label: 'দাগের পরিমাণ', visible: true, order: 9, type: 'text' as const, width: 130 },
  { id: 'remarks', label: 'মন্তব্য', visible: true, order: 10, type: 'text' as const, width: 160 },
];
